<?php
if(!isset($_GET['f'])) { $typeform = ''; }
else {
    if($_GET['f'] == 'a') { $typeform = 'a'; }
    if($_GET['f'] == 'b') { $typeform = 'b'; }
    if($_GET['f'] == 'cdefhi') { $typeform = 'cdefhi'; }
    if($_GET['f'] == 'g') { $typeform = 'g'; }
}

?>
<div class="page" style="line-height: 1.35em;">
   <div style="float:left; width:785px; border:1px solid #B6B6B6; height:720px; margin-bottom:10px;">
       <div style="float:left; width:775px; background-color: #B6B6B6; font-size: 16px; color: #FFFFFF; font-weight: bold; padding:5px;">
	    Nous contacter par email
       </div>
       <div style="float:left; width:785px;">
	   <div style="float:left; width:200px; height:308px; border-right:1px solid #B6B6B6;">
	       <img src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/contact-enveloppe.jpg" />
	   </div>
	   <div style="float:left; width:555px;">
	       <?php if($typeform == '') { ?>
	       <div style="float:left; width:545px; padding:5px;">
		<strong style="font-size:14px;">Merci de choisir la proposition qui convient le mieux à votre besoin :</strong>
	       </div>
	       <?php // Ma commande ?>
	       <div style="float:left; padding:5px; padding-left:10px; background-color: #B6B6B6; font-size: 16px; color: #FFFFFF; font-weight: bold; border-right:1px solid #000000;">
		   1
	       </div>
	       <div style="float:left; padding:5px; font-size: 16px; font-weight: bold;">
		MA COMMANDE
	       </div>
	       <div style="float:left; margin-left:30px; width:100%; line-height: 2em;">
		<img style="vertical-align:middle;" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/puce_barre_recherche.png" /> <a href="<?php echo Mage::getBaseUrl(); ?>contacts/?t=a&f=a" class="contact-link">J'ai des questions concernant le suivi de ma commande</a><br />
		<img style="vertical-align:middle;" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/puce_barre_recherche.png" /> <a href="<?php echo Mage::getBaseUrl(); ?>contacts/?t=b&f=b" class="contact-link">Je souhaite demander l'annulation de ma commande</a><br />
		<img style="vertical-align:middle;" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/puce_barre_recherche.png" /> <a href="<?php echo Mage::getBaseUrl(); ?>sav" class="contact-link">Je veux entrer en contact avec le Service Après Vente</a><br />
	       </div>
	       <?php // Renseignement produits ?>
	       <div style="float:left; margin-top:20px; padding:5px; padding-left:10px; background-color: #B6B6B6; font-size: 16px; color: #FFFFFF; font-weight: bold; border-right:1px solid #000000;">
		   2
	       </div>
	       <div style="float:left; margin-top:20px; padding:5px; font-size: 16px; font-weight: bold;">
		J'AI BESOIN DE RENSEIGNEMENTS SUR VOS PRODUITS
	       </div>
	       <div style="float:left; margin-left:30px; width:100%; line-height: 2em;">
		<img style="vertical-align:middle;" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/puce_barre_recherche.png" /> <a href="<?php echo Mage::getBaseUrl(); ?>contacts/?t=c&f=cdefhi" class="contact-link">J'ai des questions sur un produit technique</a><br />
		<img style="vertical-align:middle;" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/puce_barre_recherche.png" /> Je me demande quelle taille choisir : <a href="<?php echo Mage::getBaseUrl(); ?>informations-tailles-habillement" class="contact-link">Habillement</a> - <a href="<?php echo Mage::getBaseUrl(); ?>info-taille-equipement-pilote" class="contact-link">Equipement pilote</a><br />
		<img style="vertical-align:middle;" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/puce_barre_recherche.png" /> <a href="<?php echo Mage::getBaseUrl(); ?>contacts/?t=d&f=cdefhi" class="contact-link">Je souhaite demander un devis</a><br />
	       </div>
	       <?php // Autres demandes ?>
	       <div style="float:left; margin-top:20px; padding:5px; padding-left:10px; background-color: #B6B6B6; font-size: 16px; color: #FFFFFF; font-weight: bold; border-right:1px solid #000000;">
		   3
	       </div>
	       <div style="float:left; margin-top:20px; padding:5px; font-size: 16px; font-weight: bold;">
		AUTRES DEMANDES
	       </div>
	       <div style="float:left; margin-left:30px; width:100%; line-height: 2em;">
		<img style="vertical-align:middle;" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/puce_barre_recherche.png" /> <a href="<?php echo Mage::getBaseUrl(); ?>contacts/?t=e&f=cdefhi" class="contact-link">J'ai des questions sur l'utilisation du site</a><br />
		<img style="vertical-align:middle;" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/puce_barre_recherche.png" /> <a href="<?php echo Mage::getBaseUrl(); ?>contacts/?t=f&f=cdefhi" class="contact-link">Je voudrais proposer un partenariat</a><br />
		<img style="vertical-align:middle;" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/puce_barre_recherche.png" /> <a href="<?php echo Mage::getBaseUrl(); ?>contacts/?t=g&f=g" class="contact-link">Je souhaite participer à votre programme d'affiliation</a><br />
		<img style="vertical-align:middle;" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/puce_barre_recherche.png" /> <a href="<?php echo Mage::getBaseUrl(); ?>contacts/?t=h&f=cdefhi" class="contact-link">Je souhaite vous proposer mes produits</a><br />
		<img style="vertical-align:middle;" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/puce_barre_recherche.png" /> <a href="<?php echo Mage::getBaseUrl(); ?>contacts/?t=i&f=cdefhi" class="contact-link">J'ai une autre demande</a><br />
	       </div>
	       <?php }

	       // Formulaire type A
	       if($typeform == 'a') {
	       ?>
		<div style="float:left; width:545px; padding:5px;">
		    <form id="form-a" name="form-a" method="post" action="<?php echo Mage::getBaseUrl(); ?>contact-submit">
		    <?php
		    // Gestion du type de demande
		    if($_GET['t'] == 'a') {
			?>
			<input type="hidden" id="typedemande" name="typedemande" value="suivi" />
			<?php
		    }
		    ?>
		    <strong style="font-size:12px;">
			OBJET :<br />
			J'ai des questions concernant le suivi de ma commande
		    </strong>
		    <br /><br />

		    <div style="float:left; width:545px;">
			<table>
			    <tr>
				<td>
				    <strong>Votre civilité</strong><span style="font-weight:bold; color:#F9B808;">*</span>
				    &nbsp;&nbsp;&nbsp;&nbsp;<input name="civ" type="radio" value="Mlle" checked="true" /> Mademoiselle
				    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input name="civ" type="radio" value="Mme" /> Madame
				    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input name="civ" type="radio" value="Mr" /> Monsieur
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre nom</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre prénom</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					</tr>
					<tr>
					    <td style="width:250px;"><input type="text" class="" name="nom" id="nom" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					    <td style="width:250px;"><input type="text" name="prenom" id="prenom" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre email</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre téléphone</strong></td>
					</tr>
					<tr>
					    <td style="width:250px;"><input type="text" name="email" id="email" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					    <td style="width:250px;"><input type="text" name="tel" id="tel" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				   <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre numéro de commande</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					</tr>
					<tr>
					    <td style="width:500px;"><input type="text" name="numcmd" id="numcmd" style="width:470px; border:1px solid #B6B6B6; padding:2px;" /></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre message</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					</tr>
					<tr>
					    <td style="width:500px;"><textarea name="message" id="message" cols="45" rows="10" style="width:470px; border:1px solid #B6B6B6; padding:2px;"></textarea></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="width:250px;">
					       <span style="font-weight:bold; color:#F9B808;">*</span> <strong>Champs obligatoires</strong>
					    </td>
					    <td style="text-align:right; width:230px; padding-top:5px;">
						<div style="float:left;">
						    <span style="font-weight:bold; color:#F9B808;"><</span> <a href="<?php echo Mage::getBaseUrl(); ?>contacts/" class="contact-link">Retour</a>
						</div>
						<input type="image" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/contact-btn-valider.png" />
					    </td>
					</tr>
				    </table>
				</td>
			    </tr>
			</table>
		    </div>
		    </form>
		</div>
	       <script>
		jQuery(document).ready(function() {
		   jQuery("#form-a").validate({
		      rules: {
			 "civ":{
			    "required": true
			 },
			 "nom":{
			    "required": true
			 },
			 "prenom":{
			    "required": true
			 },
			 "email": {
			    "required": true,
			    "email": true,
			    "maxlength": 255
			 },
			 "numcmd": {
			    "required": true
			 },
			 "message": {
			    "required": true
			 }
		      },
		      errorPlacement: function(error, element) {
			//error.insertBefore(element.prev());
			element.addClass('validation-failed');
			}

		  })
		});
		</script>
	       <?php
	       }
		?>

	       <?php
	       // Formulaire type B
	       if($typeform == 'b') {
	       ?>
		<div style="float:left; width:545px; padding:5px;">
		    <form id="form-b" name="form-b" method="post" action="<?php echo Mage::getBaseUrl(); ?>contact-submit">
		    <?php
		    // Gestion du type de demande
		    if($_GET['t'] == 'b') {
			?>
			<input type="hidden" id="typedemande" name="typedemande" value="annulation" />
			<?php
		    }
		    ?>
		    <strong style="font-size:12px;">
			OBJET :<br />
			Je souhaite demander l'annulation de ma commande
		    </strong>
		    <br /><br />
		    <div style="float:left; width:545px;">
			<table>
			    <tr>
				<td>
				    <strong>Votre civilité</strong><span style="font-weight:bold; color:#F9B808;">*</span>
				    &nbsp;&nbsp;&nbsp;&nbsp;<input name="civ" type="radio" value="Mlle" checked="true" /> Mademoiselle
				    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input name="civ" type="radio" value="Mme" /> Madame
				    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input name="civ" type="radio" value="Mr" /> Monsieur
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre nom</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre prénom</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					</tr>
					<tr>
					    <td style="width:250px;"><input type="text" class="" name="nom" id="nom" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					    <td style="width:250px;"><input type="text" name="prenom" id="prenom" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre email</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre téléphone</strong></td>
					</tr>
					<tr>
					    <td style="width:250px;"><input type="text" name="email" id="email" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					    <td style="width:250px;"><input type="text" name="tel" id="tel" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				   <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre numéro de commande</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					</tr>
					<tr>
					    <td style="width:500px;"><input type="text" name="numcmd" id="numcmd" style="width:470px; border:1px solid #B6B6B6; padding:2px;" /></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Raison de votre demande d'annulation</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					</tr>
					<tr>
					    <td style="width:500px;">
						<input name="raison" type="radio" value="delai trop important" checked="true" /> Délai trop important<br />
						<input name="raison" type="radio" value="ne veux plus le produit" /> Je ne souhaite plus ce produit<br />
						<input name="raison" type="radio" value="erreur commande" /> Je me suis trompé dans ma commande<br />
					    </td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre message</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					</tr>
					<tr>
					    <td style="width:500px;"><textarea name="message" id="message" cols="45" rows="10" style="width:470px; border:1px solid #B6B6B6; padding:2px;"></textarea></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="width:250px;">
					       <span style="font-weight:bold; color:#F9B808;">*</span> <strong>Champs obligatoires</strong>
					    </td>
					    <td style="text-align:right; width:230px; padding-top:5px;">
						<div style="float:left;">
						    <span style="font-weight:bold; color:#F9B808;"><</span> <a href="<?php echo Mage::getBaseUrl(); ?>contacts/" class="contact-link">Retour</a>
						</div>
						<input type="image" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/contact-btn-valider.png" />
					    </td>
					</tr>
				    </table>
				</td>
			    </tr>
			</table>
		    </div>
		    </form>
		</div>
	       <script>
		jQuery(document).ready(function() {
		   jQuery("#form-b").validate({
		      rules: {
			 "civ":{
			    "required": true
			 },
			 "nom":{
			    "required": true
			 },
			 "prenom":{
			    "required": true
			 },
			 "email": {
			    "required": true,
			    "email": true,
			    "maxlength": 255
			 },
			 "numcmd": {
			    "required": true
			 },
			 "raison": {
			    "required": true
			 },
			 "message": {
			    "required": true
			 }
		      },
		      errorPlacement: function(error, element) {
			//error.insertBefore(element.prev());
			element.addClass('validation-failed');
			}

		  })
		});
		</script>
	       <?php
	       }
		?>

	       <?php
	       // Formulaire type C,D,E,F,H,I
	       if($typeform == 'cdefhi') {
	       ?>
		<div style="float:left; width:545px; padding:5px;">
		    <form id="form-b" name="form-b" method="post" action="<?php echo Mage::getBaseUrl(); ?>contact-submit">
		    <?php // Gestion du type de demande ?>
		    <?php if($_GET['t'] == 'c') { ?>
			<input type="hidden" id="typedemande" name="typedemande" value="technique" />
			<strong style="font-size:12px;">
			    OBJET :<br />
			    J'ai des questions sur un produit technique
			</strong>
		    <?php } ?>
		    <?php if($_GET['t'] == 'd') { ?>
			<input type="hidden" id="typedemande" name="typedemande" value="devis" />
			<strong style="font-size:12px;">
			    OBJET :<br />
			    Je souhaite demander un devis
			</strong>
			<?php } ?>
		    <?php if($_GET['t'] == 'e') { ?>
			<input type="hidden" id="typedemande" name="typedemande" value="site" />
			<strong style="font-size:12px;">
			    OBJET :<br />
			    J'ai des questions sur l'utilisation du site
			</strong>
			<?php } ?>
		    <?php if($_GET['t'] == 'f') { ?>
			<input type="hidden" id="typedemande" name="typedemande" value="partenariat" />
			<strong style="font-size:12px;">
			    OBJET :<br />
			    Je voudrais proposer un partenariat
			</strong>
			<?php } ?>
		    <?php if($_GET['t'] == 'h') { ?>
			<input type="hidden" id="typedemande" name="typedemande" value="produit" />
			<strong style="font-size:12px;">
			    OBJET :<br />
			    Je souhaite vous proposer mes produits
			</strong>
			<?php } ?>
		    <?php if($_GET['t'] == 'i') { ?>
			<input type="hidden" id="typedemande" name="typedemande" value="autres" />
			<strong style="font-size:12px;">
			    OBJET :<br />
			    J'ai une autre demande
			</strong>
			<?php } ?>

		    <br /><br />
		    <div style="float:left; width:545px;">
			<table>
			    <tr>
				<td>
				    <strong>Votre civilité</strong><span style="font-weight:bold; color:#F9B808;">*</span>
				    &nbsp;&nbsp;&nbsp;&nbsp;<input name="civ" type="radio" value="Mlle" checked="true" /> Mademoiselle
				    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input name="civ" type="radio" value="Mme" /> Madame
				    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input name="civ" type="radio" value="Mr" /> Monsieur
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre nom</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre prénom</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					</tr>
					<tr>
					    <td style="width:250px;"><input type="text" class="" name="nom" id="nom" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					    <td style="width:250px;"><input type="text" name="prenom" id="prenom" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre email</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre téléphone</strong></td>
					</tr>
					<tr>
					    <td style="width:250px;"><input type="text" name="email" id="email" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					    <td style="width:250px;"><input type="text" name="tel" id="tel" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre message</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					</tr>
					<tr>
					    <td style="width:500px;"><textarea name="message" id="message" cols="45" rows="10" style="width:470px; border:1px solid #B6B6B6; padding:2px;"></textarea></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="width:250px;">
					       <span style="font-weight:bold; color:#F9B808;">*</span> <strong>Champs obligatoires</strong>
					    </td>
					    <td style="text-align:right; width:230px; padding-top:5px;">
						<div style="float:left;">
						    <span style="font-weight:bold; color:#F9B808;"><</span> <a href="<?php echo Mage::getBaseUrl(); ?>contacts/" class="contact-link">Retour</a>
						</div>
						<input type="image" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/contact-btn-valider.png" />
					    </td>
					</tr>
				    </table>
				</td>
			    </tr>
			</table>
		    </div>
		    </form>
		</div>
	       <script>
		jQuery(document).ready(function() {
		   jQuery("#form-b").validate({
		      rules: {
			 "civ":{
			    "required": true
			 },
			 "nom":{
			    "required": true
			 },
			 "prenom":{
			    "required": true
			 },
			 "email": {
			    "required": true,
			    "email": true,
			    "maxlength": 255
			 },
			 "message": {
			    "required": true
			 }
		      },
		      errorPlacement: function(error, element) {
			//error.insertBefore(element.prev());
			element.addClass('validation-failed');
			}

		  })
		});
		</script>
	       <?php
	       }
		?>

	       <?php
	       // Formulaire type G
	       if($typeform == 'g') {
	       ?>
		<div style="float:left; width:545px; padding:5px;">
		    <form id="form-g" name="form-g" method="post" action="<?php echo Mage::getBaseUrl(); ?>contact-submit">
		    <?php
		    // Gestion du type de demande
		    if($_GET['t'] == 'g') {
			?>
			<input type="hidden" id="typedemande" name="typedemande" value="affiliation" />
			<?php
		    }
		    ?>
		    <strong style="font-size:12px;">
			OBJET :<br />
			Je souhaite participer à votre programme d'affiliation
		    </strong>
		    <br /><br />
		    <div style="float:left;">
			Pour participer à notre programme d’affiliation, merci de nous indiquer vos coordonnées, le nom et l'url du site sur lequel vous souhaitez utiliser notre programme<br />
			Nous vous répondrons rapidement.
		    </div>
		    <br /><br />
		    <div style="float:left; width:545px;">
			<table>
			    <tr>
				<td>
				    <strong>Votre civilité</strong><span style="font-weight:bold; color:#F9B808;">*</span>
				    &nbsp;&nbsp;&nbsp;&nbsp;<input name="civ" type="radio" value="Mlle" checked="true" /> Mademoiselle
				    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input name="civ" type="radio" value="Mme" /> Madame
				    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input name="civ" type="radio" value="Mr" /> Monsieur
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre nom</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre prénom</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					</tr>
					<tr>
					    <td style="width:250px;"><input type="text" class="" name="nom" id="nom" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					    <td style="width:250px;"><input type="text" name="prenom" id="prenom" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre email</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre téléphone</strong></td>
					</tr>
					<tr>
					    <td style="width:250px;"><input type="text" name="email" id="email" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					    <td style="width:250px;"><input type="text" name="tel" id="tel" style="width:220px; border:1px solid #B6B6B6; padding:2px;" /></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="height:30px; vertical-align: bottom;"><strong>Votre message</strong><span style="font-weight:bold; color:#F9B808;">*</span></td>
					</tr>
					<tr>
					    <td style="width:500px;"><textarea name="message" id="message" cols="45" rows="10" style="width:470px; border:1px solid #B6B6B6; padding:2px;"></textarea></td>
					</tr>
				    </table>
				</td>
			    </tr>
			    <tr>
				<td>
				    <table>
					<tr>
					    <td style="width:250px;">
					       <span style="font-weight:bold; color:#F9B808;">*</span> <strong>Champs obligatoires</strong>
					    </td>
					    <td style="text-align:right; width:230px; padding-top:5px;">
						<div style="float:left;">
						    <span style="font-weight:bold; color:#F9B808;"><</span> <a href="<?php echo Mage::getBaseUrl(); ?>contacts/" class="contact-link">Retour</a>
						</div>
						<input type="image" src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/contact-btn-valider.png" />
					    </td>
					</tr>
				    </table>
				</td>
			    </tr>
			</table>
		    </div>
		    </form>
		</div>
	       <script>
		jQuery(document).ready(function() {
		   jQuery("#form-g").validate({
		      rules: {
			 "civ":{
			    "required": true
			 },
			 "nom":{
			    "required": true
			 },
			 "prenom":{
			    "required": true
			 },
			 "email": {
			    "required": true,
			    "email": true,
			    "maxlength": 255
			 },
			 "message": {
			    "required": true
			 }
		      },
		      errorPlacement: function(error, element) {
			//error.insertBefore(element.prev());
			element.addClass('validation-failed');
			}

		  })
		});
		</script>
	       <?php
	       }
		?>

	   </div>
       </div>
   </div>
   <div style="float:right; width:185px; height:720px; margin-bottom:10px;">
       <div style="float:left; width:100%; margin-bottom:10px; border:1px solid #B6B6B6;">
	   <div style="float:left; width:175px; background-color: #B6B6B6; font-size: 16px; color: #FFFFFF; font-weight: bold; padding:5px;">
		Par téléphone
	   </div>
	   <div style="float:left; width:175px; padding:5px;">
	       <strong>Question ? Conseil ?<br />Vous cherchez un produit ?</strong><br />Appelez-nous...
	       <br /><br />
	       <strong>Depuis la France</strong><br />
	       <span style="color:#0982ED; font-size: 22px; font-weight: bold;">0 494 885 790</span>
	       <br /><br />
	       Depuis l'international<br />
	       <span style="color:#0982ED; font-size: 16px; font-weight: bold;">+33 494 885 790</span>
	       <br /><br />
	       Par fax<br />
	       <span style="color:#0982ED; font-size: 16px; font-weight: bold;">0 494 328 001</span>
	   </div>
       </div>
       <div style="float:left; width:100%; border:1px solid #B6B6B6;">
	   <div style="float:left; width:175px; background-color: #B6B6B6; font-size: 16px; color: #FFFFFF; font-weight: bold; padding:5px;">
		Dans nos boutiques
	   </div>
	   <div style="float:left; width:175px; height:405px; padding:5px;">
	       <span style="color:#0982ED; font-size: 12px; font-weight: bold;">Circuit Paul Ricard HTTT</span> <br />
	       RDN8 2760 Route des Hauts du Camp<br />
	       83330 Le Castellet <br />
	       <br /><br />
	       <strong>Horaires d'ouverture :</strong><br />
	       Du lundi au vendredi<br />
	       De 10h à 18h<br /><br />
	       <div style="width:100%; text-align: center;">
		   <a href="http://g.co/maps/ugm6z" target="_blank"><img src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/contact-btn-plan.png" /></a>
	       </div>
	       <br /><br />
	       <span style="color:#0982ED; font-size: 12px; font-weight: bold;">Oreca-Store</span> <br />
	       Parc d'activité de Signes<br />
	       Avenue de Rome<br />
	       83870 SIGNES
	       <br /><br />
	       <strong>Horaires d'ouverture :</strong><br />
	       Du mardi au samedi<br />
	       De 10h à 19h<br /><br />
	       <div style="width:100%; text-align: center;">
		   <a href="http://g.co/maps/u4642" target="_blank"><img src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/default/oreca/images/contact-btn-plan.png" /></a>
	       </div>
	   </div>
       </div>
   </div>
</div>

