<?php
$tabmarques = array();
?>
<div id="afftitreVehicule" style="float:left; display:none;">Votre véhicule : </div><!--<div id="affmarqueVehicule" style="float:left;"></div><div id="affmodeleVehicule" style="float:left;"></div><div id="afftypeVehicule" style="float:left;"></div><div id="affanneeVehicule" style="float:left;"></div>-->
<div style="float:left;">
<select id="marqueVehicule" style="margin-bottom:8px; width:120px;" name="marqueVehicule" onchange="getOptions('modeleVehicule', jQuery('#marqueVehicule').val());">
    <option value="">Marque</option>
<?php
$catracine = Mage::getModel('catalog/category')->load(1288);
foreach ($catracine->getChildrenCategories() as $childCategory) {
    ?>
    <option value="<?php echo $childCategory->getId(); ?>"><?php echo $childCategory->getName(); ?></option>
    <?php
}
?>
</select>
<?php //echo $catracine->getUrl(); ?>
<select id="modeleVehicule" disabled="disabled" style="margin-bottom:8px; width:120px;" name="modeleVehicule" onchange="getOptions('typeVehicule', jQuery('#modeleVehicule').val());">
    <option value="">Modèle</option>
</select>

<select id="typeVehicule" disabled="disabled" style="margin-bottom:8px; width:120px;" name="typeVehicule" onchange="getOptions('anneeVehicule', jQuery('#typeVehicule').val());">
    <option value="">Type</option>
</select>

<select id="anneeVehicule" disabled="disabled" style="margin-bottom:8px; width:120px;" name="anneeVehicule" onchange="initBtn();">
    <option value="">Année</option>
</select>
</div>
	<div id="rechvehvalid" class="rechveh-btn-off" style="float:left; background:url() no-repeat 0 0 #595959; font-size:12px; margin-top:0px; margin-left:10px; width:100px; height:20px;" onclick="">
	    VALIDER
	</div>
	

<script type="text/javascript">
jQuery(document).ready(function() {
   var vehicule = jQuery.cookie("vehicule");
   if(vehicule) {
       var cats = vehicule.split(',');
       jQuery('#marqueVehicule option[value='+cats[0]+']').attr("selected", "selected");
       populDrops('modeleVehicule', cats[0], cats[1]);
       populDrops('typeVehicule', cats[1], cats[2]);
       populDrops('anneeVehicule', cats[2], cats[3]);
       //jQuery('#rechvehvalid').css('display','block');
       //jQuery('#affmarqueVehicule').html(jQuery('#marqueVehicule option:selected').text());
       jQuery('#afftitreVehicule').css('display','block');
       initBtn();
       
   }
});

function initBtn() {
    jQuery('#rechvehvalid').removeClass('rechveh-btn-off');
    jQuery('#rechvehvalid').addClass('rechveh-btn');
    jQuery('#rechvehvalid').css('display','block');
    jQuery('#rechvehvalid').click(function(){
       gotoCategory(jQuery('#anneeVehicule').val());
   });
}

function resetBtn() {
    jQuery('#rechvehvalid').removeClass('rechveh-btn');
    jQuery('#rechvehvalid').addClass('rechveh-btn-off');
    jQuery('#rechvehvalid').css('display','none');
    jQuery('#rechvehvalid').click(function(){
       
   });
}

function populDrops(name, id, selectedid) {
    jQuery.ajax({
	type: "GET",
	url: "<?php echo Mage::getBaseUrl(); ?>services/rechercheparvehicule/get_options.php",
	data: "id="+id,
	success: function(json){
	    //alert('Selection de '+id+' - json : '+msg);
	    var attribs = eval('(' + json + ')');
	    jQuery.each(attribs, function(indexatt, valueatt) {
		jQuery('#'+name).append(
		    jQuery('<option></option>').val(indexatt).html(valueatt)
		);
		//jQuery('#aff'+name).html(valueatt);
	    });
	    jQuery('#'+name).removeAttr('disabled');
	    jQuery('#'+name+' option[value='+selectedid+']').attr("selected", "selected");
	},
	error: function(msg){
	    //alert("Aucun véhicule ne correspond à votre sélection actuelle.");
	}
    });
}

function getOptions(name, id) {
    jQuery.ajax({
	type: "GET",
	url: "<?php echo Mage::getBaseUrl(); ?>services/rechercheparvehicule/get_options.php",
	data: "id="+id,
	success: function(json){
	    //alert('Selection de '+id+' - json : '+msg);
	    if (name == 'modeleVehicule') {
		jQuery('#modeleVehicule').empty();
		jQuery('#modeleVehicule').append(
		    jQuery('<option></option>').val('').html('Modèle')
		);
		jQuery('#typeVehicule').empty();
		jQuery('#typeVehicule').append(
		    jQuery('<option></option>').val('').html('Type')
		);
		jQuery('#anneeVehicule').empty();
		jQuery('#anneeVehicule').append(
		    jQuery('<option></option>').val('').html('Année')
		);
		jQuery('#modeleVehicule').attr('disabled', true);
		jQuery('#typeVehicule').attr('disabled', true);
		jQuery('#anneeVehicule').attr('disabled', true);
		//jQuery('#rechvehvalid').css('display','none');
		resetBtn();
	    }
	    if (name == 'typeVehicule') {
		jQuery('#typeVehicule').empty();
		jQuery('#typeVehicule').append(
		    jQuery('<option></option>').val('').html('Type')
		);
		jQuery('#anneeVehicule').empty();
		jQuery('#anneeVehicule').append(
		    jQuery('<option></option>').val('').html('Année')
		);
		jQuery('#typeVehicule').attr('disabled', true);
		jQuery('#anneeVehicule').attr('disabled', true);
		//jQuery('#rechvehvalid').css('display','none');
		resetBtn();
	    }
	    if (name == 'anneeVehicule') {
		jQuery('#anneeVehicule').empty();
		jQuery('#anneeVehicule').append(
		    jQuery('<option></option>').val('').html('Année')
		);
		jQuery('#anneeVehicule').attr('disabled', true);
		//jQuery('#rechvehvalid').css('display','none');
		resetBtn();
		
	    }
	    //jQuery('#'+name).empty();
	    var attribs = eval('(' + json + ')');
	    jQuery.each(attribs, function(indexatt, valueatt) {
		jQuery('#'+name).append(
		    jQuery('<option></option>').val(indexatt).html(valueatt)
		);
	    });
	    //jQuery('#'+name).removeAttr('disabled');
	    jQuery('#'+name).attr('disabled', false);
	},
	error: function(msg){
	    //alert("Aucun véhicule ne correspond à votre sélection actuelle.");
	}
    });
}

function gotoCategory(id) {
    var vehicule = jQuery('#marqueVehicule').val()+','+jQuery('#modeleVehicule').val()+','+jQuery('#typeVehicule').val()+','+jQuery('#anneeVehicule').val();
    jQuery.cookie("vehicule", vehicule, { expires: 365 });
    jQuery.ajax({
	type: "GET",
	url: "<?php echo Mage::getBaseUrl(); ?>services/rechercheparvehicule/get_cat_url.php",
	data: "id="+id,
	success: function(url){
	    jQuery(location).attr('href',url);
	},
	error: function(msg){
	    //alert("Aucun véhicule ne correspond à votre sélection actuelle.");
	}
    });
}
</script>
   