<?php
function getOptions($id){
    $tabcats = array();

    $catracine = Mage::getModel('catalog/category')->load($id);
    //echo $catracine->getName()." - ".$catracine->getId();
    foreach ($catracine->getChildrenCategories() as $childCategory) {
	//var_dump($childCategory->getIsActive());
	if ($childCategory->getIsActive()) {
	    $tabcats[$childCategory->getId()] = $childCategory->getName();
	}
    }
    return $tabcats;
}

function getOptionName($id){
      $catracine = Mage::getModel('catalog/category')->load($id);
    return $catracine->getName();
}
?>

<div class="titre-panier" style="margin-top:0px;">
    Recherche par véhicule
</div>

<div class="titre-totals" style="width:1000px;">
Trouvez toutes les pièces pour votre véhicule
</div>


    <div class="contenu-gris" style="height:135px;">
	<div class="rechveh-select-container bord-droit">
	    <div class="rechveh-titre-petit">
		Sélectionnez votre
	    </div>
	    <div class="rechveh-titre-gros">
		MARQUE
	    </div>
	    <?php
	    $tabmarques = array();
	    $tabmarquesseo = array();
	    ?>
	    <select id="marqueVehicule" style="margin-bottom:8px; width:220px;" name="marqueVehicule" onchange="getOptions('modeleVehicule', jQuery('#marqueVehicule').val());">
		<option value="">Marque</option>
	    <?php
	    $catracine = Mage::getModel('catalog/category')->load(1288);
	    foreach ($catracine->getChildrenCategories() as $childCategory) {
		$tabmarquesseo[$childCategory->getId()] = $childCategory->getName();
		?>
		<option value="<?php echo $childCategory->getId(); ?>"><?php echo $childCategory->getName(); ?></option>
		<?php
	    }
	    ?>
	    </select>
	</div>
	<div class="rechveh-select-container bord-droit bord-gauche">
	    <div class="rechveh-titre-petit">
		Sélectionnez votre
	    </div>
	    <div class="rechveh-titre-gros">
		MODELE
	    </div>
	    <select id="modeleVehicule" disabled="disabled" style="margin-bottom:8px; width:220px;" name="modeleVehicule" onchange="getOptions('typeVehicule', jQuery('#modeleVehicule').val());">
		<option value="">Modèle</option>
	    </select>
	</div>
	<div class="rechveh-select-container bord-droit bord-gauche">
	    <div class="rechveh-titre-petit">
		Sélectionnez votre
	    </div>
	    <div class="rechveh-titre-gros">
		TYPE
	    </div>
	    <select id="typeVehicule" disabled="disabled" style="margin-bottom:8px; width:220px;" name="typeVehicule" onchange="getOptions('anneeVehicule', jQuery('#typeVehicule').val());">
		<option value="">Type</option>
	    </select>
	</div>
	<div class="rechveh-select-container bord-gauche">
	    <div class="rechveh-titre-petit">
		Sélectionnez votre
	    </div>
	    <div class="rechveh-titre-gros">
		ANNEE
	    </div>
	    <select id="anneeVehicule" disabled="disabled" style="margin-bottom:8px; width:220px;" name="anneeVehicule" onchange="initBtn();">
		<option value="">Année</option>
	    </select>
	</div>
    </div>
	<div class="rechveh-container-btn">
	    <div id="rechvehvalid" class="rechveh-btn-off" style="float:left; width:125px; margin-left:438px; margin-bottom:5px; margin-top:5px;" onclick="">
		VALIDER
	    </div>
	</div>
	<div class="rechveh-container-contacts">
	    <div class="titre-totals" style="width:365px; font-size:13px; line-height:1.3em; height:36px;">
		Vous ne trouvez pas les articles pour votre voiture ?
		<br />
		Contactez nos conseillers :
	    </div>
	    <div class="contenu-gris" style="width:365px; height:165px;">
		<div class="rechveh-select-container bord-droit" style="width:181px; text-align:center; margin-top:10px; height:155px;">
		    <img src="<?php echo $this->getSkinUrl('images/rechveh_phone.jpg'); ?>" />
		    <div class="rechveh-titre-petit">
			Par téléphone
		    </div>
		    <div style="color:#F86D04; font-size:24px; font-weight:bold;">
			0 494 885 790
		    </div>
		</div>
		<div class="rechveh-select-container bord-gauche" style="width:181px; text-align:center; margin-top:10px; height:155px;">
		    <img src="<?php echo $this->getSkinUrl('images/rechveh_mail.jpg'); ?>" />
		    <div class="rechveh-titre-petit" style="margin-top:18px;">
			Par Email
		    </div>
		    <a href="<?php echo Mage::getBaseUrl(); ?>contacts"><button class="rechveh-btn-email"><span style="color:#F86D04;">></span> Formulaire de contact</button></a>
		</div>
	    </div>
	</div>
	<div class="rechveh-container-manuel">
	    <span style="font-size:16px; font-weight:bold;">Comment utiliser la recherche par véhicule ?</span>
	    <br />
	    <span style="font-size:12px; color:#F86D04; font-weight:bold;">
		- Sélectionnez la marque, le modèle, le type puis l'année correspondant à votre véhicule
	    </span>
	    <br />
	    <span style="font-size:12px;">
		Votre véhicule n'apparait pas dans la liste ? Pas d'inquiétude ! Contactez simplement notre service client au 0 494 885 790, nous ferons tout pour apporter une réponse à votre recherche.
	    </span>
	    <br /><br />
	    <span style="font-size:12px; color:#F86D04; font-weight:bold;">
		- Vous pouvez ainsi consulter l'intégralité des produits adaptés à votre voiture
	    </span>
	    <br />
	    <span style="font-size:12px;">
	    Vous avez besoin de consulter le détail d'un article ? Cliquez simplement sur son nom ou sa photo
	    <br />
	    
	    </span>
	</div>
	<div style="float:left; margin-top:10px;">
	    <!-- Bouton IAdvize -->
	    <?php
	    // Restrictions horaire
	    $getdate = getdate();
	    $jour = date('D', Mage::app()->getLocale()->storeTimeStamp());
	    $listejours = array('Mon','Tue','Wed','Thu','Fri','Sat');
	    $horairedebut = "8";
	    $horairefin = "19";
	    if (in_array($jour,$listejours)) {
		if ($getdate['hours'] >= $horairedebut && $getdate['hours'] < $horairefin) {

		    ?>
	    <div style="float:left; padding-left:15px; padding-bottom:15px; display:block;">
		<script type="text/javascript">
		var iproto = (("https:" == document.location.protocol) ? "https://" : "http://");
		document.write(unescape("%3Cscript src='" + iproto + "livechat.iadvize.com/chat_button.js?bid=767' type='text/javascript'%3E%3C/script%3E"));
		</script>
	    </div>
	    <?php

		}
	    }
	    ?>
	</div>
	<!--<div style="clear:both; height:10px;"></div>-->
	<div class="titre-totals" style="width:1000px; margin-top:30px;">
	    PIECES DETACHEES DE VEHICULE
	</div>
	


<script type="text/javascript">
jQuery(document).ready(function() {
   var vehicule = jQuery.cookie("vehicule");
   if(vehicule) {
       var cats = vehicule.split(',');
       jQuery('#marqueVehicule option[value='+cats[0]+']').attr("selected", "selected");
       populDrops('modeleVehicule', cats[0], cats[1]);
       populDrops('typeVehicule', cats[1], cats[2]);
       populDrops('anneeVehicule', cats[2], cats[3]);
       //jQuery('#rechvehvalid').css('display','block');
       initBtn();

   }
});

function initBtn() {
    jQuery('#rechvehvalid').removeClass('rechveh-btn-off');
    jQuery('#rechvehvalid').addClass('rechveh-btn');
    jQuery('#rechvehvalid').click(function(){
       gotoCategory(jQuery('#anneeVehicule').val());
   });
}

function resetBtn() {
    jQuery('#rechvehvalid').removeClass('rechveh-btn');
    jQuery('#rechvehvalid').addClass('rechveh-btn-off');
    jQuery('#rechvehvalid').click(function(){

   });
}

function populDrops(name, id, selectedid) {
    jQuery.ajax({
	type: "GET",
	url: "<?php echo Mage::getBaseUrl(); ?>services/rechercheparvehicule/get_options.php",
	data: "id="+id,
	success: function(json){
	    //alert('Selection de '+id+' - json : '+msg);
	    var attribs = eval('(' + json + ')');
	    jQuery.each(attribs, function(indexatt, valueatt) {
		jQuery('#'+name).append(
		    jQuery('<option></option>').val(indexatt).html(valueatt)
		);
	    });
	    jQuery('#'+name).removeAttr('disabled');
	    jQuery('#'+name+' option[value='+selectedid+']').attr("selected", "selected");
	},
	error: function(msg){
	    alert("Aucun véhicule ne correspond à votre sélection actuelle.");
	}
    });
}

function getOptions(name, id) {
    jQuery.ajax({
	type: "GET",
	url: "<?php echo Mage::getBaseUrl(); ?>services/rechercheparvehicule/get_options.php",
	data: "id="+id,
	success: function(json){
	    //alert('Selection de '+id+' - json : '+msg);
	    if (name == 'modeleVehicule') {
		jQuery('#modeleVehicule').empty();
		jQuery('#modeleVehicule').append(
		    jQuery('<option></option>').val('').html('Modèle')
		);
		jQuery('#typeVehicule').empty();
		jQuery('#typeVehicule').append(
		    jQuery('<option></option>').val('').html('Type')
		);
		jQuery('#anneeVehicule').empty();
		jQuery('#anneeVehicule').append(
		    jQuery('<option></option>').val('').html('Année')
		);
		jQuery('#modeleVehicule').attr('disabled', true);
		jQuery('#typeVehicule').attr('disabled', true);
		jQuery('#anneeVehicule').attr('disabled', true);
		//jQuery('#rechvehvalid').css('display','none');
		resetBtn();
	    }
	    if (name == 'typeVehicule') {
		jQuery('#typeVehicule').empty();
		jQuery('#typeVehicule').append(
		    jQuery('<option></option>').val('').html('Type')
		);
		jQuery('#anneeVehicule').empty();
		jQuery('#anneeVehicule').append(
		    jQuery('<option></option>').val('').html('Année')
		);
		jQuery('#typeVehicule').attr('disabled', true);
		jQuery('#anneeVehicule').attr('disabled', true);
		//jQuery('#rechvehvalid').css('display','none');
		resetBtn();
	    }
	    if (name == 'anneeVehicule') {
		jQuery('#anneeVehicule').empty();
		jQuery('#anneeVehicule').append(
		    jQuery('<option></option>').val('').html('Année')
		);
		jQuery('#anneeVehicule').attr('disabled', true);
		//jQuery('#rechvehvalid').css('display','none');
		resetBtn();

	    }
	    //jQuery('#'+name).empty();
	    var attribs = eval('(' + json + ')');
	    jQuery.each(attribs, function(indexatt, valueatt) {
		jQuery('#'+name).append(
		    jQuery('<option></option>').val(indexatt).html(valueatt)
		);
	    });
	    //jQuery('#'+name).removeAttr('disabled');
	    jQuery('#'+name).attr('disabled', false);
	},
	error: function(msg){
	    //alert("Aucun véhicule ne correspond à votre sélection actuelle.");
	}
    });
}

function gotoCategory(id) {
    var vehicule = jQuery('#marqueVehicule').val()+','+jQuery('#modeleVehicule').val()+','+jQuery('#typeVehicule').val()+','+jQuery('#anneeVehicule').val();
    jQuery.cookie("vehicule", vehicule, { expires: 365 });
    jQuery.ajax({
	type: "GET",
	url: "<?php echo Mage::getBaseUrl(); ?>services/rechercheparvehicule/get_cat_url.php",
	data: "id="+id,
	success: function(url){
	    jQuery(location).attr('href',url);
	},
	error: function(msg){
	    //alert("Aucun véhicule ne correspond à votre sélection actuelle.");
	}
    });
}
</script>

<?php //Special Google :p
if(isset($_GET['prod'])) { $prd = $_GET['prod']; } else { $prd = ''; }
if(isset($_GET['marque'])) { $mar = $_GET['marque']; } else { $mar = ''; }
if(isset($_GET['modele'])) { $mod = $_GET['modele']; } else { $mod = ''; }
if(isset($_GET['type'])) { $typ = $_GET['type']; } else { $typ = ''; }
if(isset($_GET['annee'])) { $ann = $_GET['annee']; } else { $ann = ''; }

?>
<?php
if ($prd == '') {
?>
	<div class="hpseo-autrescats-container" style="margin-top:15px;">
	    <div class="hpseo-autrescats-titre">
		<h2>LE FREINAGE</h2>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Disque de frein Groupe N (GRN)" class="hpitemnormal">Disques de frein Groupe N (GRN)</a></h3>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Disque de frein rainurés percés" class="hpitemnormal">Disque de frein rainurés percés</a></h3>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Plaquettes de frein" class="hpitemnormal">Plaquettes de frein</a></h3>
	    </div>
	</div>

	<div class="hpseo-autrescats-container" style="margin-top:15px;">
	    <div class="hpseo-autrescats-titre">
		<h2>L'HABITACLE</h2>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Fixations de siège" class="hpitemnormal">Fixations de siège</a></h3>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Arceaux" class="hpitemnormal">Arceaux</a></h3>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Moyeux" class="hpitemnormal">Moyeux</a></h3>
	    </div>
	</div>

	<div class="hpseo-autrescats-container" style="margin-top:15px;">
	    <div class="hpseo-autrescats-titre">
		<h2>MOTEUR</h2>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Admission air" class="hpitemnormal">Admission air</a></h3>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Allumage" class="hpitemnormal">Allumage</a></h3>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Circuit essence" class="hpitemnormal">Circuit essence</a></h3>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Circuit huile" class="hpitemnormal">Circuit huile</a></h3>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Circuit eau" class="hpitemnormal">Circuit eau</a></h3>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Echappement" class="hpitemnormal">Echappement</a></h3>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Pièces moteur" class="hpitemnormal">Pièces moteur</a></h3>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Transmission" class="hpitemnormal">Transmission</a></h3>
	    </div>
	    <div class="hpseo-autrescats-contenu">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=Durites" class="hpitemnormal">Durites</a></h3>
	    </div>
	</div>

<?php
}
else {
    ?>
<div class="hpseo-autrescats-container" style="margin-top:15px;">
	    <div class="hpseo-autrescats-titre">
		<h2>MOTEUR</h2>
	    </div>


    <?php
    //echo "<div class='seo-rech-veh-niv2' style='margin-top:5px; float:left;'><h1>$prd</h1>";
   if ($mar == '') {

	foreach($tabmarquesseo as $idmq=>$mq) {

	    //echo "<h2><a href='http://www.oreca-store.com/choix-par-vehicule?prod=".$prd."&marque=".$mq."' onclick='resetVehicule();'>".$prd." pour ".$mq."</a></h2>";
	    ?>
	    <div class="hpseo-autrescats-contenu" style="height:auto;">
		<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=<?php echo $prd; ?>&marque=<?php echo $idmq; ?>" class="hpitemnormal"><?php echo $prd; ?> pour <?php echo $mq; ?></a></h3>
	    </div>
	<?php
	}
    } else {
	if ($mod == '') {
	    $mq = getOptionName($mar);
	    foreach(getOptions($mar) as $idmod=>$mod) {
		?>
		<div class="hpseo-autrescats-contenu"  style="height:auto;">
		    <h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=<?php echo $prd; ?>&marque=<?php echo $mar; ?>&modele=<?php echo $idmod; ?>" class="hpitemnormal"><?php echo $prd; ?> pour <?php echo $mq; ?> <?php echo $mod; ?></a></h3>
		</div>
		<?php
	    }
	    //$req = "SELECT DISTINCT modele FROM catalog_product_vehicules WHERE marque = '$mar'";
	    //$res = mysql_query($req);
//	    while($row = mysql_fetch_assoc($res)) {
//		echo "<h2><a href='http://www.oreca-store.com/choix-par-vehicule?prod=".$prd."&marque=".$mar."&modele=".$row['modele']."'>".$prd." pour ".$mar." ".$row['modele']."</a></h2>";
//	    }
	}
	else {
	    if ($typ == '') {
		$mq = getOptionName($mar);
		$modele = getOptionName($mod);
		foreach(getOptions($mod) as $idtype=>$type) {
		    ?>
		    <div class="hpseo-autrescats-contenu"  style="height:auto;">
			<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=<?php echo $prd; ?>&marque=<?php echo $mar; ?>&modele=<?php echo $mod; ?>&type=<?php echo $idtype; ?>" class="hpitemnormal"><?php echo $prd; ?> pour <?php echo $mq; ?> <?php echo $modele; ?> <?php echo $type; ?></a></h3>
		    </div>
		    <?php
		}
		/*
		$req = "SELECT DISTINCT type FROM catalog_product_vehicules WHERE marque = '$mar' AND modele = '$mod'";
		$res = mysql_query($req);
		while($row = mysql_fetch_assoc($res)) {
		    echo "<h2><a href='http://www.oreca-store.com/choix-par-vehicule?prod=".$prd."&marque=".$mar."&modele=".$mod."&type=".$row['type']."'>".$prd." pour ".$mar." ".$mod." ".$row['type']."</a></h2>";
		}
		 * 
		 */
	    }
	    else {
		if ($ann == '') {
		    $mq = getOptionName($mar);
		    $modele = getOptionName($mod);
		    $type = getOptionName($typ);
		    foreach(getOptions($typ) as $idann=>$annee) {
			$catdest = Mage::getModel('catalog/category')->load($idann);
			?>
			<div class="hpseo-autrescats-contenu"  style="height:auto;">
			    <!--<h3><a href="<?php echo Mage::getBaseUrl(); ?>choix-par-vehicule?prod=<?php echo $prd; ?>&marque=<?php echo $mar; ?>&modele=<?php echo $mod; ?>&type=<?php echo $typ; ?>&annee=<?php echo $idann; ?>" class="hpitemnormal"><?php echo $prd; ?> pour <?php echo $mq; ?> <?php echo $modele; ?> <?php echo $type; ?> <?php echo $annee; ?></a></h3>-->
			    <h3><a href="<?php echo $catdest->getUrl(); ?>" class="hpitemnormal"><?php echo $prd; ?> pour <?php echo $mq; ?> <?php echo $modele; ?> <?php echo $type; ?> <?php echo $annee; ?></a></h3>
			</div>
			<?php
		    }
		    /*
		    $req = "SELECT DISTINCT annee FROM catalog_product_vehicules WHERE marque = '$mar' AND modele = '$mod' AND type = '$typ'";
		    $res = mysql_query($req);
		    while($row = mysql_fetch_assoc($res)) {
			$liste_vehicules = $mar." ".$mod." ".$typ." ".$row['annee'];
			$reqv = "SELECT option_id FROM eav_attribute_option_value WHERE value = '$liste_vehicules'
				    AND option_id IN
					(SELECT option_id FROM eav_attribute_option
					WHERE attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'liste_vehicules'))";
			$resv = mysql_query($reqv);
			$vehid = @mysql_result($resv, 0);
			echo "<h2><a href='http://www.oreca-store.com/choix-par-vehicule?liste_vehicules=".$vehid."'>".$prd." pour ".$liste_vehicules."</a></h2>";
		    }
		     *
		     */
		}
	    }
	}
    }
    //echo "</div>";
}
?>
</div>

