<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
include('/var/www/magento/services/conf/database_connection.php');
$datenow = date('Y-m-d H:i:s');
$req = "SELECT * FROM banner_supersized WHERE datedebut < '$datenow' AND datefin > '$datenow' ORDER BY position ASC";
$res = mysql_query($req);

$banners = "";
//echo $req;
while($row = mysql_fetch_assoc($res)) {
    $banners .= "{image : 'http://192.168.1.248/magento/media/banners/".$row['banniere']."', thumb : 'http://192.168.1.248/magento/media/banners/".$row['vignette']."', title : '".$row['nom']."', url : '".$row['lien']."'},"; 
}
$banners = substr($banners, 0, -1);
?>
<script type="text/javascript">

jQuery(function($){
        $.supersized({

                //Functionality
                slideshow               :   1,		//Slideshow on/off
                autoplay		:   1,		//Slideshow starts playing automatically
                start_slide             :   1,		//Start slide (0 is random)
                random			:   0,		//Randomize slide order (Ignores start slide)
                slide_interval          :   6000,	//Length between transitions
                transition              :   1, 		//0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
                transition_speed	:   500,	//Speed of transition
                new_window		:   0,		//Image links open in new window/tab
                pause_hover             :   0,		//Pause slideshow on hover
                keyboard_nav            :   1,		//Keyboard navigation on/off
                performance		:   1,		//0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
                image_protect		:   1,		//Disables image dragging and right click with Javascript
                image_path		:   'img/',     //Default image path

                //Size & Position
                min_width		:   2000,	//Min width allowed (in pixels)
                min_height              :   430,	//Min height allowed (in pixels)
                vertical_center         :   0,		//Vertically center background
                horizontal_center       :   1,		//Horizontally center background
                fit_portrait         	:   0,		//Portrait images will not exceed browser height
                fit_landscape		:   0,		//Landscape images will not exceed browser width

                //Components
                slide_links             :   'name',
                thumb_links             :   1,
                navigation              :   1,		//Slideshow controls on/off
                thumbnail_navigation    :   0,		//Thumbnail navigation
                slide_counter           :   0,		//Display slide numbers
                slide_captions          :   1,		//Slide caption (Pull from "title" in slides array)
                slides 			:  [            //Slideshow Images
					    <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('hpbanners')->toHtml() ?>
                                            <?php echo $banners; ?>
					]


        });

});
</script>
