<script type="text/javascript">
function disabledEventPropagation(event)
{
   if (event.stopPropagation){
       event.stopPropagation();
   }
   else if(window.event){
      window.event.cancelBubble=true;
   }
}
</script>

<div class="hpproducts-container">
    <div class="hpproducts-passion">
	
	<div class="hpproducts-vignette" onclick="window.location.href='http://192.168.1.248/magento/chemise-vintage-carreaux-gulf.html';">
	    <div class="vignprod-promotion"></div>
	    <div class="vignprod-apercu" id="vignprodapercu">
		<!--<a href="http://192.168.1.248/magento/chemise-vintage-carreaux-gulf.html" rel="#overlay" style="text-decoration:none" onclick="disabledEventPropagation(event);">-->
		<img title="Aperçu rapide" alt="Aperçu rapide" src="http://192.168.1.248/magento/skin/frontend/default/oreca/images/vignprod_apercu_over.png"
		     href="http://192.168.1.248/magento/services/popup_produit.php?id=43699" rel="#overlay"
		     onclick="disabledEventPropagation(event);"
		     />
		<!--</a>-->
	    </div>
	    
	    <div class="vignprod-photo">
		<img title="Chemise Vintage à carreaux Gulf" alt="Chemise Vintage à carreaux Gulf" src="http://192.168.1.248/magento/media/catalog/product/cache/6/image/220x220/9df78eab33525d08d6e5fb8d27136e95/G/P/GPO-Vintage-Shirt.jpg" width="220" height="220" />
	    </div>
	    <div class="vignprod-name">
		<a href="http://192.168.1.248/magento/chemise-vintage-carreaux-gulf.html" onclick="disabledEventPropagation(event);">Chemise Vintage à carreaux Gulf</a>
	    </div>
	    <div class="vignprod-marque">
		<img src="http://192.168.1.248/magento/media/marques/GULF.gif" width="60px" height="60px" />
	    </div>
	    <div class="vignprod-pastillepromo" style="display:block;">
		<div class="remise-texte">-49</div><div class="remise-pcent">%</div>
	    </div>
	    <div class="vignprod-prix">
		<div class="apartirde" style="display:block;">A partir de</div>
		<div class="prix-barre" style="display:block;">69,91 €</div>
		<div class="prix-normal">35,88 €</div>
	    </div>
	</div>
	
	<div class="hpproducts-vignette" onclick="window.location.href='http://192.168.1.248/magento/gant-de-conduite-gulf.html';">
	    <div class="vignprod-destockage"></div>
	    <div class="vignprod-apercu" id="vignprodapercu">
		<!--<a href="http://192.168.1.248/magento/gant-de-conduite-gulf.html" rel="#overlay" style="text-decoration:none" onclick="disabledEventPropagation(event);">-->
		<img title="Aperçu rapide" alt="Aperçu rapide" src="http://192.168.1.248/magento/skin/frontend/default/oreca/images/vignprod_apercu_over.png"
		     href="http://192.168.1.248/magento/services/popup_produit.php?id=43704" rel="#overlay"
		     onclick="disabledEventPropagation(event);"
		     />
		<!--</a>-->
	    </div>
	    
	    <div class="vignprod-photo">
		<img title="Gant de conduite Gulf" alt="Gant de conduite Gulf" src="http://192.168.1.248/magento/media/catalog/product/cache/6/image/220x220/9df78eab33525d08d6e5fb8d27136e95/g/p/gpo-gloves.jpg" width="220" height="220" />
	    </div>
	    <div class="vignprod-name">
		<a href="http://192.168.1.248/magento/gant-de-conduite-gulf.html" onclick="disabledEventPropagation(event);">Gant de conduite Gulf</a>
	    </div>
	    <div class="vignprod-marque">
		<img src="http://192.168.1.248/magento/media/marques/GULF.gif" width="60px" height="60px" />
	    </div>
	    <div class="vignprod-pastillepromo" style="display:none;">
		<div class="remise-texte">-0</div><div class="remise-pcent">%</div>
	    </div>
	    <div class="vignprod-prix">
		<div class="apartirde" style="display:none;">A partir de</div>
		<div class="prix-barre" style="display:none;">59,00 €</div>
		<div class="prix-normal">59,00 €</div>
	    </div>
	</div>
	
	<div class="hpproducts-vignette" onclick="window.location.href='http://192.168.1.248/magento/sac-gulf-bally.html';">
	    <div class="vignprod-"></div>
	    <div class="vignprod-apercu" id="vignprodapercu">
		<!--<a href="http://192.168.1.248/magento/sac-gulf-bally.html" rel="#overlay" style="text-decoration:none" onclick="disabledEventPropagation(event);">-->
		<img title="Aperçu rapide" alt="Aperçu rapide" src="http://192.168.1.248/magento/skin/frontend/default/oreca/images/vignprod_apercu_over.png"
		     href="http://192.168.1.248/magento/services/popup_produit.php?id=43717" rel="#overlay"
		     onclick="disabledEventPropagation(event);"
		     />
		<!--</a>-->
	    </div>
	    
	    <div class="vignprod-photo">
		<img title="Sac Gulf bally" alt="Sac Gulf bally" src="http://192.168.1.248/magento/media/catalog/product/cache/6/image/220x220/9df78eab33525d08d6e5fb8d27136e95/r/e/retrobag1.jpg" width="220" height="220" />
	    </div>
	    <div class="vignprod-name">
		<a href="http://192.168.1.248/magento/sac-gulf-bally.html" onclick="disabledEventPropagation(event);">Sac Gulf bally</a>
	    </div>
	    <div class="vignprod-marque">
		<img src="http://192.168.1.248/magento/media/marques/GULF.gif" width="60px" height="60px" />
	    </div>
	    <div class="vignprod-pastillepromo" style="display:none;">
		<div class="remise-texte">-0</div><div class="remise-pcent">%</div>
	    </div>
	    <div class="vignprod-prix">
		<div class="apartirde" style="display:none;">A partir de</div>
		<div class="prix-barre" style="display:none;">129,00 €</div>
		<div class="prix-normal">129,00 €</div>
	    </div>
	</div>
	
	<div class="hpproducts-vignette" onclick="window.location.href='http://192.168.1.248/magento/set-de-stickers-gulf.html';">
	    <div class="vignprod-destockage"></div>
	    <div class="vignprod-apercu" id="vignprodapercu">
		<!--<a href="http://192.168.1.248/magento/set-de-stickers-gulf.html" rel="#overlay" style="text-decoration:none" onclick="disabledEventPropagation(event);">-->
		<img title="Aperçu rapide" alt="Aperçu rapide" src="http://192.168.1.248/magento/skin/frontend/default/oreca/images/vignprod_apercu_over.png"
		     href="http://192.168.1.248/magento/services/popup_produit.php?id=43714" rel="#overlay"
		     onclick="disabledEventPropagation(event);"
		     />
		<!--</a>-->
	    </div>
	    
	    <div class="vignprod-photo">
		<img title="Set de stickers Gulf" alt="Set de stickers Gulf" src="http://192.168.1.248/magento/media/catalog/product/cache/6/image/220x220/9df78eab33525d08d6e5fb8d27136e95/i/l/ilovegpo.jpg" width="220" height="220" />
	    </div>
	    <div class="vignprod-name">
		<a href="http://192.168.1.248/magento/set-de-stickers-gulf.html" onclick="disabledEventPropagation(event);">Set de stickers Gulf</a>
	    </div>
	    <div class="vignprod-marque">
		<img src="http://192.168.1.248/magento/media/marques/GULF.gif" width="60px" height="60px" />
	    </div>
	    <div class="vignprod-pastillepromo" style="display:none;">
		<div class="remise-texte">-0</div><div class="remise-pcent">%</div>
	    </div>
	    <div class="vignprod-prix">
		<div class="apartirde" style="display:none;">A partir de</div>
		<div class="prix-barre" style="display:none;">6,00 €</div>
		<div class="prix-normal">6,00 €</div>
	    </div>
	</div>
	    </div>
    <div class="hpproducts-pratique">
	
	<div class="hpproducts-vignette" onclick="window.location.href='http://192.168.1.248/magento/protection-acoustique-sparco-pour-casque-intregral.html';">
	    <div class="vignprod-destockage"></div>
	    <div class="vignprod-apercu" id="vignprodapercu">
		<img title="Aperçu rapide" alt="Aperçu rapide" src="http://192.168.1.248/magento/skin/frontend/default/oreca/images/vignprod_apercu_over.png"
		     href="http://192.168.1.248/magento/services/popup_produit.php?id=32197" rel="#overlay"
		     onclick="disabledEventPropagation(event);" id=""
		     />
	    </div>

	    <div class="vignprod-photo">
		<img title="Protection acoustique SPARCO pour Casque Intrégral" alt="Protection acoustique SPARCO pour Casque Intrégral" src="http://192.168.1.248/magento/media/catalog/product/cache/6/image/220x220/9df78eab33525d08d6e5fb8d27136e95/k/i/kit_de_protection_acoustique.jpg" width="220" height="220" />
	    </div>
	    <div class="vignprod-name">
		<a href="http://192.168.1.248/magento/protection-acoustique-sparco-pour-casque-intregral.html" onclick="disabledEventPropagation(event);">Protection acoustique SPARCO pour Casque Intrégral</a>
	    </div>
	    <div class="vignprod-marque">
		<img src="http://192.168.1.248/magento/media/marques/SPARCO.gif" width="60px" height="60px" />
	    </div>
	    <div class="vignprod-pastillepromo" style="display:none;">
		<div class="remise-texte">-0</div><div class="remise-pcent">%</div>
	    </div>
	    <div class="vignprod-prix">
		<div class="apartirde" style="display:none;">A partir de</div>
		<div class="prix-barre" style="display:none;">9,90 €</div>
		<div class="prix-normal">9,90 €</div>
	    </div>
	</div>
	
	<div class="hpproducts-vignette" onclick="window.location.href='http://192.168.1.248/magento/casque-stilo-trophy-des-rallye.html';">
	    <div class="vignprod-"></div>
	    <div class="vignprod-apercu" id="vignprodapercu">
		<img title="Aperçu rapide" alt="Aperçu rapide" src="http://192.168.1.248/magento/skin/frontend/default/oreca/images/vignprod_apercu_over.png"
		     href="http://192.168.1.248/magento/services/popup_produit.php?id=32173" rel="#overlay"
		     onclick="disabledEventPropagation(event);" id=""
		     />
	    </div>

	    <div class="vignprod-photo">
		<img title="Casque STILO Trophy DES Rallye" alt="Casque STILO Trophy DES Rallye" src="http://192.168.1.248/magento/media/catalog/product/cache/6/image/220x220/9df78eab33525d08d6e5fb8d27136e95/j/e/jet_rally.jpg" width="220" height="220" />
	    </div>
	    <div class="vignprod-name">
		<a href="http://192.168.1.248/magento/casque-stilo-trophy-des-rallye.html" onclick="disabledEventPropagation(event);">Casque STILO Trophy DES Rallye</a>
	    </div>
	    <div class="vignprod-marque">
		<img src="http://192.168.1.248/magento/media/marques/STILO.gif" width="60px" height="60px" />
	    </div>
	    <div class="vignprod-pastillepromo" style="display:none;">
		<div class="remise-texte">-0</div><div class="remise-pcent">%</div>
	    </div>
	    <div class="vignprod-prix">
		<div class="apartirde" style="display:none;">A partir de</div>
		<div class="prix-barre" style="display:none;">489,00 €</div>
		<div class="prix-normal">489,00 €</div>
	    </div>
	</div>
	
	<div class="hpproducts-vignette" onclick="window.location.href='http://192.168.1.248/magento/sac-agrave-casque-bell-hans.html';">
	    <div class="vignprod-"></div>
	    <div class="vignprod-apercu" id="vignprodapercu">
		<img title="Aperçu rapide" alt="Aperçu rapide" src="http://192.168.1.248/magento/skin/frontend/default/oreca/images/vignprod_apercu_over.png"
		     href="http://192.168.1.248/magento/services/popup_produit.php?id=32196" rel="#overlay"
		     onclick="disabledEventPropagation(event);" id=""
		     />
	    </div>

	    <div class="vignprod-photo">
		<img title="Sac à casque BELL Hans" alt="Sac à casque BELL Hans" src="http://192.168.1.248/magento/media/catalog/product/cache/6/image/220x220/9df78eab33525d08d6e5fb8d27136e95/h/e/helmet_and_hans_bag_black_quilted.jpg" width="220" height="220" />
	    </div>
	    <div class="vignprod-name">
		<a href="http://192.168.1.248/magento/sac-agrave-casque-bell-hans.html" onclick="disabledEventPropagation(event);">Sac à casque BELL Hans</a>
	    </div>
	    <div class="vignprod-marque">
		<img src="http://192.168.1.248/magento/media/marques/BELL.gif" width="60px" height="60px" />
	    </div>
	    <div class="vignprod-pastillepromo" style="display:none;">
		<div class="remise-texte">-0</div><div class="remise-pcent">%</div>
	    </div>
	    <div class="vignprod-prix">
		<div class="apartirde" style="display:none;">A partir de</div>
		<div class="prix-barre" style="display:none;">79,00 €</div>
		<div class="prix-normal">79,00 €</div>
	    </div>
	</div>
	
	<div class="hpproducts-vignette" onclick="window.location.href='http://192.168.1.248/magento/casque-cuir.html';">
	    <div class="vignprod-"></div>
	    <div class="vignprod-apercu" id="vignprodapercu">
		<img title="Aperçu rapide" alt="Aperçu rapide" src="http://192.168.1.248/magento/skin/frontend/default/oreca/images/vignprod_apercu_over.png"
		     href="http://192.168.1.248/magento/services/popup_produit.php?id=31950" rel="#overlay"
		     onclick="disabledEventPropagation(event);" id=""
		     />
	    </div>

	    <div class="vignprod-photo">
		<img title="Casque Cuir" alt="Casque Cuir" src="http://192.168.1.248/magento/media/catalog/product/cache/6/image/220x220/9df78eab33525d08d6e5fb8d27136e95/6/0/607ccmm3.jpg" width="220" height="220" />
	    </div>
	    <div class="vignprod-name">
		<a href="http://192.168.1.248/magento/casque-cuir.html" onclick="disabledEventPropagation(event);">Casque Cuir</a>
	    </div>
	    <div class="vignprod-marque">
		<img src="http://192.168.1.248/magento/media/marques/NC.gif" width="60px" height="60px" />
	    </div>
	    <div class="vignprod-pastillepromo" style="display:none;">
		<div class="remise-texte">-0</div><div class="remise-pcent">%</div>
	    </div>
	    <div class="vignprod-prix">
		<div class="apartirde" style="display:none;">A partir de</div>
		<div class="prix-barre" style="display:none;">270,00 €</div>
		<div class="prix-normal">270,00 €</div>
	    </div>
	</div>
	    </div>
</div>

<!-- overlayed element -->
<div class="apple_overlay" id="overlay">

	<!-- the external content is loaded inside this tag -->
	<div class="contentWrap"></div>

</div>

<!-- make all links with the 'rel' attribute open overlays -->
<script>

jQuery(function() {

	// if the function argument is given to overlay,
	// it is assumed to be the onBeforeLoad event listener
	jQuery("#vignprodapercu img[rel]").overlay({
	//jQuery("#vignprodapercu").overlay({

		mask: 'black',
		effect: 'apple',
		api: true,

		onBeforeLoad: function() {

			// grab wrapper element inside content
			var wrap = this.getOverlay().find(".contentWrap");
			var self = this;

			// load the page specified in the trigger
			//wrap.load(this.getTrigger().attr("href"));
			wrap.load(this.getTrigger().attr("href"), function(){
			    jQuery('.close', this).click(function(){self.close()});
			});
		},

		onClose: function() {
		    jQuery('div.popup-produit-conteneur').html('');
		}

	});
	
});

</script>